# Generated by Django 6.0.7 on 2026-07-31 11:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=100)),
                ('statut', models.CharField(default='Actif', max_length=50)),
                ('date_embauche', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bureau', 'Bureau'), ('Portable', 'Portable')], max_length=20)),
                ('modele', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Disponible', 'Disponible'), ('En maintenance', 'En maintenance'), ('Hord service', 'Hord service')], max_length=50)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('garantie', models.CharField(blank=True, max_length=50, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordi.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='ordinateurs',
            field=models.ManyToManyField(blank=True, to='ordi.ordinateur'),
        ),
    ]
